# Generated by Django 2.0.1 on 2018-01-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('access_token', models.CharField(max_length=100, null=True, unique=True)),
                ('access_secret', models.CharField(max_length=100, null=True)),
                ('oauth_token', models.CharField(max_length=100, null=True, unique=True)),
                ('oauth_secret', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
