# Generated by Django 2.0.2 on 2018-02-15 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
