# Generated by Django 2.0.2 on 2018-02-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favs', '0004_auto_20180223_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fav',
            options={'get_latest_by': 'saved_at'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'get_latest_by': 'saved_at'},
        ),
        migrations.AddField(
            model_name='fav',
            name='json',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='like',
            name='json',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
