# Generated by Django 2.0.2 on 2018-02-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favs', '0005_auto_20180226_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='fav',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
